# Generated by Django 6.0.6 on 2026-06-07 22:56

import common.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('to_email', models.EmailField(max_length=254, verbose_name='to email')),
                ('template', models.CharField(help_text='Render-service template name', max_length=64, verbose_name='template')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('props', models.JSONField(default=dict, help_text='Template props passed to the renderer', verbose_name='props')),
                ('idempotency_key', models.CharField(max_length=255, unique=True, verbose_name='idempotency key')),
                ('state', models.CharField(default='pending', max_length=32, verbose_name='state')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='scheduled at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
            ],
            options={
                'verbose_name': 'outbound email',
                'verbose_name_plural': 'outbound emails',
                'indexes': [models.Index(fields=['state', 'scheduled_at'], name='outboundemail_state_sched_idx')],
            },
        ),
    ]
