# Generated by Django 6.0.6 on 2026-06-07 20:40

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('state', models.CharField(default='pending', max_length=32, verbose_name='state')),
                ('source', models.CharField(blank=True, default='', help_text='Where the signup came from (e.g. the marketing form id)', max_length=64, verbose_name='source')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='invited at')),
            ],
            options={
                'verbose_name': 'waitlist signup',
                'verbose_name_plural': 'waitlist signups',
                'indexes': [models.Index(fields=['state'], name='waitlist_wa_state_90cefb_idx')],
            },
        ),
    ]
