# Generated by Django 6.0.6 on 2026-06-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistsignup',
            name='category',
            field=models.CharField(default='unknown', help_text='What the signup is waiting for (web_ui / cloud / either); UNKNOWN until they pick on the confirmation card', max_length=32, verbose_name='category'),
        ),
        migrations.AddIndex(
            model_name='waitlistsignup',
            index=models.Index(fields=['category'], name='waitlist_wa_categor_5d87af_idx'),
        ),
    ]
