# Generated by Django 6.0.6 on 2026-06-08 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_waitlistsignup_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistsignup',
            name='source_interest_other',
            field=models.CharField(blank=True, default='', help_text="Free text when 'other' is among source_interests", max_length=120, verbose_name='source interest (other)'),
        ),
        migrations.AddField(
            model_name='waitlistsignup',
            name='source_interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='Most-wanted roadmap sources (linkedin / slack / ...); empty = no vote'),
        ),
        migrations.AlterField(
            model_name='waitlistsignup',
            name='category',
            field=models.CharField(default='unknown', help_text='Deprecated: superseded by source_interests; no longer collected', max_length=32, verbose_name='category'),
        ),
    ]
