# generated by datamodel-codegen:
#   filename:  tmp3hl0bcfy.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, Field


class ListenerWire(BaseModel):
    id: Annotated[str, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    instructions: Annotated[str, Field(title="Instructions")]
    kind: Annotated[str, Field(title="Kind")]
    delivery_mode: Annotated[str, Field(title="Delivery Mode")]
    is_active: Annotated[bool, Field(title="Is Active")]
    poll_interval_seconds: Annotated[int, Field(title="Poll Interval Seconds")]
    last_polled_at: Annotated[AwareDatetime | None, Field(title="Last Polled At")] = None
    next_poll_at: Annotated[AwareDatetime | None, Field(title="Next Poll At")] = None
    last_digest_at: Annotated[AwareDatetime | None, Field(title="Last Digest At")] = None
    next_digest_at: Annotated[AwareDatetime | None, Field(title="Next Digest At")] = None
    user_id: Annotated[str, Field(title="User Id")]
    data: Annotated[dict[str, Any] | None, Field(title="Data")] = {}
    created_at: Annotated[AwareDatetime | None, Field(title="Created At")] = None
