# generated by datamodel-codegen:
#   filename:  tmpp4qd_wo6.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import AwareDatetime, Field, RootModel

from openmagpie.api._gen_base import ListenerConfig


class EngineSpec(ListenerConfig):
    kind: Annotated[str, Field(title="Kind")]
    model: Annotated[str | None, Field(title="Model")] = ""


class LogNotifierSpec(ListenerConfig):
    kind: Annotated[Literal["log"], Field(title="Kind")] = "log"
    prefix: Annotated[str | None, Field(title="Prefix")] = "[hit]"
    include_fields: Annotated[list[str] | None, Field(title="Include Fields")] = []


class RedditSubredditStreamSpec(ListenerConfig):
    kind: Annotated[Literal["reddit_subreddit"], Field(title="Kind")] = "reddit_subreddit"
    subreddit: Annotated[str, Field(title="Subreddit")]


class StreamWatch(ListenerConfig):
    spec: Annotated[RedditSubredditStreamSpec, Field(discriminator="kind", title="Spec")]
    last_event_at: Annotated[AwareDatetime | None, Field(title="Last Event At")] = None


class WebhookNotifierSpec(ListenerConfig):
    kind: Annotated[Literal["webhook"], Field(title="Kind")] = "webhook"
    url: Annotated[str, Field(title="Url")]
    headers: Annotated[dict[str, str] | None, Field(title="Headers")] = {}
    include_fields: Annotated[list[str] | None, Field(title="Include Fields")] = []


class Notifiers(RootModel[WebhookNotifierSpec | LogNotifierSpec]):
    root: Annotated[WebhookNotifierSpec | LogNotifierSpec, Field(discriminator="kind")]


class SemanticListenerConfig(ListenerConfig):
    streams: Annotated[list[StreamWatch] | None, Field(title="Streams", validate_default=True)] = []
    refined_instructions: Annotated[str | None, Field(title="Refined Instructions")] = ""
    engine: EngineSpec | None = None
    hit_threshold: Annotated[float | None, Field(ge=0.0, le=1.0, title="Hit Threshold")] = 0.8
    notifiers: Annotated[list[Notifiers] | None, Field(title="Notifiers", validate_default=True)] = []
    digest_interval_seconds: Annotated[int | None, Field(title="Digest Interval Seconds")] = 3600


# ── generated registry (kind -> model) ──
CONFIG_BY_KIND: dict[str, type[ListenerConfig]] = {
    "semantic": SemanticListenerConfig,
}

AnyListenerConfig = SemanticListenerConfig
