# Generated by Django 6.0.6 on 2026-06-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0008_semantic_filter_engine_kind_default'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='watchactiondelivery',
            index=models.Index(fields=['created_at'], name='watchdeliv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='watchactionrun',
            index=models.Index(fields=['completed_at', 'state'], name='watchrun_completed_state_idx'),
        ),
    ]
