# Generated by Django 6.0.6 on 2026-07-07 16:30

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0010_watchactionrun_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchActionBackfill',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_id', models.CharField(max_length=26, verbose_name='account id')),
                ('watch_id', models.CharField(max_length=26, verbose_name='watch id')),
                ('target_action_id', models.CharField(max_length=26, verbose_name='target action id')),
                ('source_action_id', models.CharField(blank=True, default='', max_length=26, verbose_name='source action id')),
                ('source_is_head', models.BooleanField(default=False, verbose_name='source is head')),
                ('kind', models.CharField(default='', help_text='target WatchActionKind value', max_length=32, verbose_name='kind')),
                ('replace', models.BooleanField(default=False, verbose_name='replace')),
                ('occurred_since', models.DateTimeField(blank=True, null=True, verbose_name='occurred since')),
                ('occurred_until', models.DateTimeField(blank=True, null=True, verbose_name='occurred until')),
                ('completed_since', models.DateTimeField(blank=True, null=True, verbose_name='completed since')),
                ('completed_until', models.DateTimeField(blank=True, null=True, verbose_name='completed until')),
                ('state', models.CharField(default='pending', help_text='WatchActionBackfillState value', max_length=16, verbose_name='state')),
                ('matched', models.PositiveIntegerField(default=0, verbose_name='matched')),
                ('present', models.PositiveIntegerField(default=0, verbose_name='present')),
                ('pruned', models.PositiveIntegerField(default=0, verbose_name='pruned')),
                ('deleted', models.PositiveIntegerField(default=0, verbose_name='deleted')),
                ('enqueued', models.PositiveIntegerField(default=0, verbose_name='enqueued')),
                ('replace_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='replace deleted at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
            ],
            options={
                'verbose_name': 'watch action backfill',
                'verbose_name_plural': 'watch action backfills',
                'indexes': [models.Index(fields=['state', 'scheduled_at'], name='watchbackfill_state_sched_idx'), models.Index(fields=['account_id', 'id'], name='watchbackfill_acct_id_idx')],
            },
        ),
    ]
