"""Regenerate the CLI's typed models from the committed wire schema.

Pipeline (the "server owns the schema, client consumes" loop):

  manage.py dump_wire_schema          # server: Pydantic -> JSON Schema
        |  (make dev-wire-schema)
  cli/schema/wire_schema.json         # committed contract artifact
        |  (make dev-cli-types -> this script)
  datamodel-code-generator
        |
  api/_generated_wire.py              # transport shell (data: opaque)
  api/_generated_configs.py           # per-kind configs (roots inherit
                                       #   _gen_base.ListenerConfig) +
                                       #   CONFIG_BY_KIND / AnyListenerConfig

Two CI staleness guards make the server the single source:
  g1: `make dev-wire-schema && git diff --exit-code`  (schema vs models)
  g2: `make dev-cli-types  && git diff --exit-code`   (gen vs schema)
Without them, codegen just trades manual drift for stale-gen drift.

Reads the committed artifact (no running server needed at codegen/CI
time); refresh it from the server with `make dev-wire-schema`.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path

CLI = Path(__file__).resolve().parent.parent
API = CLI / "src" / "openmagpie" / "api"
SCHEMA = CLI / "schema" / "wire_schema.json"
WIRE_OUT = API / "_generated_wire.py"
CONFIGS_OUT = API / "_generated_configs.py"
_BASE_IMPORT = "from openmagpie.api._gen_base import ListenerConfig"

_CODEGEN = [
    "uv",
    "run",
    "datamodel-codegen",
    "--input-file-type",
    "jsonschema",
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--target-python-version",
    "3.13",
    "--use-standard-collections",
    "--use-union-operator",
    # Annotated[float, Field(ge=...)] not the deprecated confloat(...)
    # (v1-style; runtime-ok but type-checkers reject calls in type pos).
    "--use-annotated",
    "--disable-timestamp",
]

# datamodel-codegen emits a root `class Model(RootModel[Any])` for a
# bare `$defs` document (no top-level type). Dead noise; strip it.
_ROOT_ARTIFACT = "class Model(RootModel[Any]):\n    root: Any\n\n\n"

# datamodel-codegen stamps the (random temp) input filename into the
# header -> non-deterministic -> defeats the CI staleness guard.
# Normalize to a stable banner.
_GEN_BANNER = (
    "# GENERATED by scripts/gen_types.py from cli/schema/wire_schema.json.\n"
    "# Do not edit. Run `make dev-cli-types` to regenerate.\n"
)


def _stabilize_header(path: Path) -> None:
    text = path.read_text()
    marker = "from __future__ import annotations"
    path.write_text(_GEN_BANNER + "\n" + text[text.index(marker) :])


def _fetch_bundle() -> dict:
    """The committed schema artifact is the single source consumed here.
    `make dev-wire-schema` refreshes it from the server models; a CI
    guard fails if it's stale."""
    if not SCHEMA.exists():
        sys.exit(f"missing {SCHEMA} - run `make dev-wire-schema` first")
    return json.loads(SCHEMA.read_text())


def _codegen(schema: dict, out: Path) -> None:
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
        json.dump(schema, f)
        src = f.name
    subprocess.run([*_CODEGEN, "--input", src, "--output", str(out)], check=True)


def _scope_base(path: Path, kind_titles: list[str]) -> None:
    """Make ONLY the per-kind root models inherit the discoverability
    base (datamodel-codegen's `--base-class` is global and would also
    rebase nested helpers like StreamWatch, which are not configs).
    Deterministic: the kind titles come from the schema bundle."""
    text = path.read_text()
    for title in kind_titles:
        text = text.replace(f"class {title}(BaseModel):", f"class {title}(ListenerConfig):")
    # Inject the base import just after the `from __future__` line.
    anchor = "from __future__ import annotations\n"
    text = text.replace(anchor, anchor + "\n" + _BASE_IMPORT + "\n", 1)
    path.write_text(text)


def main() -> None:
    bundle = _fetch_bundle()

    # 1. Transport + envelope models (one $defs doc). `data` stays an
    #    opaque object -> dict[str, Any].
    _codegen(bundle["wire"], WIRE_OUT)
    WIRE_OUT.write_text(WIRE_OUT.read_text().replace(_ROOT_ARTIFACT, "", 1))
    _stabilize_header(WIRE_OUT)

    # 2. Per-kind configs into one $defs doc (refs are `#/$defs/<Model>`,
    #    pydantic default ref_template, so they resolve merged).
    combined: dict = {"$defs": {}}
    for kind, schema in bundle["configs"].items():
        combined["$defs"].update(schema.get("$defs", {}))
        title = bundle["config_titles"][kind]
        combined["$defs"][title] = {k: v for k, v in schema.items() if k != "$defs"}
    _codegen(combined, CONFIGS_OUT)
    CONFIGS_OUT.write_text(CONFIGS_OUT.read_text().replace(_ROOT_ARTIFACT, "", 1))
    _stabilize_header(CONFIGS_OUT)

    titles = bundle["config_titles"]
    _scope_base(CONFIGS_OUT, list(titles.values()))

    # 3. kind -> model map + union, generated (no hand-maintained list).
    union = " | ".join(titles[k] for k in titles) or "ListenerConfig"
    footer = [
        "",
        "",
        "# -- generated registry (kind -> model) --",
        "CONFIG_BY_KIND: dict[str, type[ListenerConfig]] = {",
        *[f'    "{k}": {titles[k]},' for k in titles],
        "}",
        "",
        f"AnyListenerConfig = {union}",
        "",
    ]
    with CONFIGS_OUT.open("a") as fh:
        fh.write("\n".join(footer))

    subprocess.run(
        ["uv", "run", "ruff", "format", str(WIRE_OUT), str(CONFIGS_OUT)],
        check=True,
    )
    subprocess.run(
        [
            "uv",
            "run",
            "ruff",
            "check",
            "--fix",
            "--quiet",
            str(WIRE_OUT),
            str(CONFIGS_OUT),
        ],
        check=False,
    )
    print(f"generated: {WIRE_OUT.name}, {CONFIGS_OUT.name}")


if __name__ == "__main__":
    sys.exit(main())
