# Generated by Django 6.0.6 on 2026-06-12 01:12

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_unique_oauth_application_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliToken',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user_id', models.CharField(db_index=True, help_text='The id of the user this token authenticates as.', max_length=26, verbose_name='user id')),
                ('name', models.CharField(help_text="Human label so the owner can tell tokens apart (e.g. 'home-office box').", max_length=255, verbose_name='name')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='token hash')),
                ('last_four', models.CharField(max_length=4, verbose_name='last four')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
            ],
            options={
                'verbose_name': 'CLI token',
                'verbose_name_plural': 'CLI tokens',
            },
        ),
    ]
