# Generated by Django 6.0.6 on 2026-06-22 20:43

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySettings',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('mode', models.CharField(default='unset', max_length=16)),
                ('instance_id', models.CharField(blank=True, default='', max_length=36)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
