# Generated by Django 6.0.6 on 2026-06-30 17:22

import telemetry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_backfill_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrysettings',
            name='instance_id',
            field=models.CharField(blank=True, default=telemetry.models._new_instance_id, max_length=36),
        ),
    ]
