# Generated by Django 6.0.6 on 2026-07-22 19:03

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='code')),
                ('url', models.TextField(verbose_name='destination url')),
            ],
            options={
                'verbose_name': 'short link',
                'verbose_name_plural': 'short links',
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', common.fields.ULIDField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('short_link_id', models.CharField(max_length=26, verbose_name='short link id')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='ip hash')),
                ('country', models.CharField(blank=True, default='', max_length=2, verbose_name='country')),
                ('props', models.JSONField(default=dict, verbose_name='props')),
            ],
            options={
                'verbose_name': 'click event',
                'verbose_name_plural': 'click events',
                'indexes': [models.Index(fields=['short_link_id', 'country'], name='clickevent_link_country_idx')],
            },
        ),
    ]
