// Generate src/generated.ts (zod 4) from the shared contract artifact.
//
// The contract is emitted by the Python side (tools/schema_sync) into
// packages/openmagpie-schema/schema.json. This turns that one JSON Schema into
// named, cross-referencing zod schemas + inferred types, so the web validates
// API responses against the SAME definitions the server serializes. Never edit
// src/generated.ts by hand.
//
//   node scripts/generate.mjs          # write src/generated.ts
//   node scripts/generate.mjs --check  # exit non-zero if it's stale

import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { jsonSchemaToZod } from "json-schema-to-zod";

// The contract lives in the OUTER monorepo (a Python workspace); this is a
// nested pnpm workspace, so the generator reaches across the boundary. Resolve
// the repo root via git (the pattern web/apps/marketing/scripts already use)
// rather than counting `../` from this file: works from any cwd, survives the
// package moving, and fails loudly outside a checkout. The artifact path
// (packages/openmagpie-schema/schema.json) is a stable, named location.
const ROOT = execSync("git rev-parse --show-toplevel").toString().trim();
const CONTRACT = join(ROOT, "packages/openmagpie-schema/schema.json");
const OUTPUT = new URL("../src/generated.ts", import.meta.url);

const doc = JSON.parse(readFileSync(CONTRACT, "utf8"));
const defs = doc.$defs;
const names = Object.keys(defs);

// Collect the $defs each def references (for topological ordering).
function refsIn(node, acc = new Set()) {
  if (node && typeof node === "object") {
    if (typeof node.$ref === "string") acc.add(node.$ref.split("/").pop());
    for (const v of Object.values(node)) refsIn(v, acc);
  }
  return acc;
}
const deps = Object.fromEntries(
  names.map((n) => [n, [...refsIn(defs[n])].filter((d) => d !== n && defs[d])]),
);

// Topological order so a const is defined before it's referenced (Kahn).
const order = [];
const placed = new Set();
let progress = true;
while (order.length < names.length && progress) {
  progress = false;
  for (const n of names) {
    if (placed.has(n)) continue;
    if (deps[n].every((d) => placed.has(d))) {
      order.push(n);
      placed.add(n);
      progress = true;
    }
  }
}
const cyclic = names.filter((n) => !placed.has(n));
order.push(...cyclic);

const constName = (node) => `${node.$ref.split("/").pop()}Schema`;

// Node-level overrides (json-schema-to-zod calls this before its own parsing):
// (1) a oneOf carrying an OpenAPI discriminator becomes a real
//     z.discriminatedUnion (the tool ignores the discriminator keyword and would
//     otherwise emit a verbose z.any().superRefine);
// (2) a $ref becomes a reference to its named const (lazy only for cycle back-edges);
// (3) a date-time string becomes zod 4's z.iso.datetime (the tool still emits the
//     deprecated z.string().datetime() even under --zodVersion 4). `offset: true`
//     mirrors the tool's default and matches the server's tz-aware ISO output.
const parserOverride = (schema) => {
  const tag = schema?.discriminator?.propertyName;
  if (tag && Array.isArray(schema.oneOf) && schema.oneOf.every((m) => m.$ref)) {
    return `z.discriminatedUnion("${tag}", [${schema.oneOf.map(constName).join(", ")}])`;
  }
  if (schema && typeof schema.$ref === "string") {
    return cyclic.length ? `z.lazy(() => ${constName(schema)})` : constName(schema);
  }
  if (schema?.type === "string" && schema.format === "date-time") {
    return "z.iso.datetime({ offset: true })";
  }
};

let out =
  "// GENERATED by @magpie/schema (node scripts/generate.mjs). Do not edit by hand.\n" +
  "// Source: openmagpie-schema (Pydantic) -> packages/openmagpie-schema/schema.json -> zod.\n" +
  'import { z } from "zod";\n\n';
for (const name of order) {
  const body = jsonSchemaToZod(defs[name], {
    parserOverride,
    module: "none",
    noImport: true,
    withJsdocs: true,
    zodVersion: "4",
  });
  out += `export const ${name}Schema = ${body};\n`;
  out += `export type ${name} = z.infer<typeof ${name}Schema>;\n\n`;
}

// Strip trailing whitespace the tool leaves on some lines so the committed
// artifact passes the repo's whitespace check (formatting hygiene, not a
// content rewrite).
out = out.replace(/[ \t]+$/gm, "");

if (process.argv.includes("--check")) {
  const current = readFileSync(OUTPUT, "utf8");
  if (current !== out) {
    process.stderr.write("src/generated.ts is stale. Run `pnpm --filter @magpie/schema generate` and commit.\n");
    process.exit(1);
  }
} else {
  const { writeFileSync } = await import("node:fs");
  writeFileSync(OUTPUT, out);
  process.stderr.write(`Wrote src/generated.ts (${order.length} schemas).\n`);
}
